/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/toggle-feature': {
    put: operations['toggleFeature']
  }
  '/schedule/unlink-offences': {
    post: operations['unlinkOffences']
  }
  '/schedule/link-offences/{schedulePartId}': {
    post: operations['linkOffences']
  }
  '/schedule/create': {
    post: operations['createSchedule']
  }
  '/schedule/by-id/{scheduleId}': {
    get: operations['findScheduleById']
  }
  '/schedule/all': {
    get: operations['findAllSchedules']
  }
  '/offences/load-results': {
    /** Get the results of the most recent load */
    get: operations['findLoadResults']
  }
  '/offences/code/{offenceCode}': {
    /** This endpoint will return the the offences that start with the passed offence code */
    get: operations['getOffencesByOffenceCode']
  }
  '/admin/feature-toggles': {
    get: operations['getAllToggles']
  }
}

export interface components {
  schemas: {
    /** @description Feature toggle details */
    FeatureToggle: {
      /**
       * @description Feature to be toggled: FULL_SYNC_NOMIS, DELTA_SYNC_NOMIS, FULL_SYNC_SDRS or DELTA_SYNC_SDRS
       * @enum {string}
       */
      feature: 'FULL_SYNC_NOMIS' | 'DELTA_SYNC_NOMIS' | 'FULL_SYNC_SDRS' | 'DELTA_SYNC_SDRS'
      /** @description true or false - depending on whether the feature should be enabled */
      enabled: boolean
    }
    /** @description Schedule part ID and Offence ID - used for unlinking offences from schedules */
    SchedulePartIdAndOffenceId: {
      /** Format: int64 */
      schedulePartId: number
      /** Format: int64 */
      offenceId: number
    }
    /** @description Offence details */
    Offence: {
      /**
       * Format: int64
       * @description Unique ID of the offence
       */
      id: number
      /** @description The offence code */
      code?: string
      /** @description The offence description */
      description?: string
      /** @description The CJS Title (usually the same as description) */
      cjsTitle?: string
      /**
       * Format: int32
       * @description The revision number of the offence
       */
      revisionId?: number
      /**
       * Format: date
       * @description The offence start date
       */
      startDate?: string
      /**
       * Format: date
       * @description The offence end date
       */
      endDate?: string
      /** @description The offence's home office stats code */
      homeOfficeStatsCode?: string
      /**
       * Format: date-time
       * @description The date this offence was last changed in SDRS
       */
      changedDate?: string
      /**
       * Format: date-time
       * @description The date this offence was loaded into manage-offences from SDRS
       */
      loadDate?: string
      /** @description The schedules linked to this offence */
      schedules?: components['schemas']['ScheduleDetails'][]
    }
    /** @description Schedule details */
    Schedule: {
      /** Format: int64 */
      id?: number
      act: string
      code: string
      url?: string
      scheduleParts?: components['schemas']['SchedulePart'][]
    }
    /** @description Schedule details */
    ScheduleDetails: {
      /** Format: int64 */
      id?: number
      act: string
      code: string
      url?: string
      schedulePartNumbers?: number[]
    }
    /** @description Schedule part details and associated offences */
    SchedulePart: {
      /** Format: int64 */
      id?: number
      /** Format: int32 */
      partNumber: number
      offences?: components['schemas']['Offence'][]
    }
    /** @description Details of the load by alpha char (A to Z) */
    MostRecentLoadResult: {
      /** @description Single alphabetic character between A and Z - indicates the part of the SDRS load this status relates to */
      alphaChar: string
      /**
       * @description Load Status: SUCCESS or FAIL
       * @enum {string}
       */
      status?: 'SUCCESS' | 'FAIL'
      /**
       * @description Load Type: FULL_LOAD or UPDATE
       * @enum {string}
       */
      type?: 'FULL_LOAD' | 'UPDATE'
      /**
       * Format: date-time
       * @description The date and time of the load
       */
      loadDate?: string
      /**
       * Format: date-time
       * @description The date and time of the most recent successful load; if the load was successful this is the same as the loadDate
       */
      lastSuccessfulLoadDate?: string
    }
  }
}

export interface operations {
  toggleFeature: {
    responses: {
      /** OK */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FeatureToggle'][]
      }
    }
  }
  unlinkOffences: {
    responses: {
      /** OK */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SchedulePartIdAndOffenceId'][]
      }
    }
  }
  linkOffences: {
    parameters: {
      path: {
        /** The schedule part ID */
        schedulePartId: number
      }
    }
    responses: {
      /** OK */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json': number[]
      }
    }
  }
  createSchedule: {
    responses: {
      /** OK */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Schedule']
      }
    }
  }
  findScheduleById: {
    parameters: {
      path: {
        /** The schedule ID */
        scheduleId: number
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['Schedule']
        }
      }
    }
  }
  findAllSchedules: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['Schedule'][]
        }
      }
    }
  }
  /** Get the results of the most recent load */
  findLoadResults: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['MostRecentLoadResult'][]
        }
      }
    }
  }
  /** This endpoint will return the the offences that start with the passed offence code */
  getOffencesByOffenceCode: {
    parameters: {
      path: {
        /** The offence code */
        offenceCode: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['Offence'][]
        }
      }
    }
  }
  getAllToggles: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['FeatureToggle'][]
        }
      }
    }
  }
}
