/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/offences/code/{offenceCode}': {
    /** This endpoint will return the the offences that match an offence code */
    get: operations['getOffencesByOffenceCode']
  }
}

export interface components {
  schemas: {
    /** @description Offence details */
    Offence: {
      /**
       * Format: int64
       * @description Unique ID of the offence
       */
      id: number
      /** @description The offence code */
      code?: string
      /** @description The offence description */
      description?: string
    }
  }
}

export interface operations {
  /** This endpoint will return the the offences that match an offence code */
  getOffencesByOffenceCode: {
    parameters: {
      path: {
        /** The offence code */
        offenceCode: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['Offence'][]
        }
      }
    }
  }
}
