enum AuthorisedRoles {
  ROLE_MANAGE_OFFENCES_ADMIN = 'ROLE_MANAGE_OFFENCES_ADMIN',
  ROLE_UPDATE_OFFENCE_SCHEDULES = 'ROLE_UPDATE_OFFENCE_SCHEDULES',
  ROLE_NOMIS_OFFENCE_ACTIVATOR = 'ROLE_NOMIS_OFFENCE_ACTIVATOR',
  NOMIS_OFFENCE_ACTIVATOR = 'NOMIS_OFFENCE_ACTIVATOR',
}

export default AuthorisedRoles
