enum FeatureToggleEnum {
  FULL_SYNC_NOMIS = 'FULL_SYNC_NOMIS',
  DELTA_SYNC_NOMIS = 'DELTA_SYNC_NOMIS',
  FULL_SYNC_SDRS = 'FULL_SYNC_SDRS',
  DELTA_SYNC_SDRS = 'DELTA_SYNC_SDRS',
  SYNC_HOME_OFFICE_CODES = 'SYNC_HOME_OFFICE_CODES',
}

export default FeatureToggleEnum
