enum FeatureToggleEnum {
  FULL_SYNC_NOMIS = 'FULL_SYNC_NOMIS',
  DELTA_SYNC_NOMIS = 'DELTA_SYNC_NOMIS',
  FULL_SYNC_SDRS = 'FULL_SYNC_SDRS',
  DELTA_SYNC_SDRS = 'DELTA_SYNC_SDRS',
  SYNC_HOME_OFFICE_CODES = 'SYNC_HOME_OFFICE_CODES',
  PUBLISH_EVENTS = 'PUBLISH_EVENTS',
  UNLINK_SCHEDULES_NOMIS = 'UNLINK_SCHEDULES_NOMIS',
  LINK_SCHEDULES_NOMIS = 'LINK_SCHEDULES_NOMIS',
  T3_OFFENCE_EXCLUSIONS = 'T3_OFFENCE_EXCLUSIONS',
}

export default FeatureToggleEnum
